travisbrown/iteratee

benchmark/src/main/scala/io/travisbrown/benchmark/Benchmark.scala, build.sbt
This is a little surprising, since this project is still a pretty literal translation at the moment:
```
[info] Benchmark                    Mode  Cnt      Score     Error  Units
[info] IterateeBenchmark.sumIntsI  thrpt   40  47430.328 ± 677.958  ops/s
[info] IterateeBenchmark.sumIntsS  thrpt   40  39906.412 ± 481.330  ops/s
```
`I` indicates this project, `S` is Scalaz, and higher numbers are better. My guess is that this is largely due to the strictness of `combine`.
=> Add initial benchmark

benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala, core/shared/src/main/scala/io/iteratee/EnumerateeModule.scala, core/shared/src/main/scala/io/iteratee/Enumerator.scala, core/shared/src/main/scala/io/iteratee/EnumeratorModule.scala, core/shared/src/main/scala/io/iteratee/Iteratee.scala, core/shared/src/main/scala/io/iteratee/IterateeModule.scala, core/shared/src/main/scala/io/iteratee/Module.scala, core/shared/src/main/scala/io/iteratee/package.scala, core/shared/src/test/scala/io/iteratee/EnumeratorSuite.scala
One minor API change (to `iterate`) and a new module setup that allows "partial application" of the type constructor for iteratees, etc.:
```scala
import io.iteratee.eval._
val it = take[String](2)
val en = enumList(List(1, 2, 3))
val f = map[Int, String](_.toString)
```
And then:
```scala
scala> it.feedE(f.wrap(en)).run
res5: cats.Eval[Vector[String]] = cats.Eval$$anon$8@3704996b
```
There's some repetition, but the convenience is worth it.
=> Add module system for convenience

benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala, core/shared/src/main/scala/io/iteratee/Enumeratee.scala, core/shared/src/main/scala/io/iteratee/EnumerateeModule.scala, core/shared/src/main/scala/io/iteratee/Enumerator.scala, core/shared/src/main/scala/io/iteratee/EnumeratorModule.scala, core/shared/src/main/scala/io/iteratee/Iteratee.scala, core/shared/src/main/scala/io/iteratee/IterateeModule.scala, core/shared/src/main/scala/io/iteratee/Step.scala, core/shared/src/main/scala/io/iteratee/package.scala, core/shared/src/test/scala/io/iteratee/ArbitraryInstances.scala, core/shared/src/test/scala/io/iteratee/EnumeratorSuite.scala, core/shared/src/test/scala/io/iteratee/EqInstances.scala, core/shared/src/test/scala/io/iteratee/IterateeSuite.scala, core/shared/src/test/scala/io/iteratee/SizedEnumerator.scala
I'd been following the traditional order of type parameters, but I think putting the type constructor first everywhere is clearer and more consistent.
=> Make type constructor first type parameter

build.sbt, core/shared/src/test/scala/io/iteratee/EnumeratorSuite.scala, core/shared/src/test/scala/io/iteratee/EqInstances.scala, core/shared/src/test/scala/io/iteratee/IterateeSuite.scala, core/shared/src/test/scala/io/iteratee/package.scala
Not sure why I need the manually-defined `MonoidalTests.Isomorphisms` instances, but oh well.
=> Upgrade to Cats 0.4.0-SNAPSHOT

core/src/main/scala/io/iteratee/Enumerator.scala, tests/jvm/src/it/scala/io/iteratee/task/TaskOperationTests.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/EqInstances.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala, tests/shared/src/test/scala/io/iteratee/EvalTests.scala, tests/shared/src/test/scala/io/iteratee/XorTests.scala
These don't really serve any good purpose—it's easy enough to use the enumeratees or iteratees directly.
=> Remove redundant helper methods on Enumerator

core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/EnumerateeModule.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala
Add a `filterK` method to `Enumeratee` that allows using monadic predicate for filtering elements.
See [gitter discussion](https://gitter.im/travisbrown/iteratee?at=56952ed0b1f439094a07b87e).
=> Add filterK to Enumeratee

benchmark/src/test/scala/io/iteratee/benchmark/InMemoryBenchmarkSpec.scala, benchmark/src/test/scala/io/iteratee/benchmark/StreamingBenchmarkSpec.scala, build.sbt
This is a follow-up to #57 that adds tests for the fs2 benchmarks and switches to using the published snapshot.
=> Add tests for fs2 benchmarks

core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/EnumerateeModule.scala, core/src/main/scala/io/iteratee/Enumerator.scala, core/src/main/scala/io/iteratee/Iteratee.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
This is both clearer and more consistent with e.g. `Kleisli`'s `flatMapF` in Cats.
=> Rename mapK to flatMapF

build.sbt, core/src/main/scala/io/iteratee/Enumerator.scala, core/src/main/scala/io/iteratee/EnumeratorModule.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala, tests/shared/src/test/scala/io/iteratee/EvalTests.scala
I'm planning an 0.3.0 release and decided that I'd like to rename `generate` and `generateM` to `iterateUntil` and `iterateUntilM` (to avoid the confusing collision with Play's naming). I've also introduced a new `generateM` that works like Play's.
/cc @Crafter6432
=> Rename generate to iterateUntil and introduce new generateM

.travis.yml, benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala, core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/EnumerateeInstances.scala, core/src/main/scala/io/iteratee/EnumerateeModule.scala, core/src/main/scala/io/iteratee/EnumeratorModule.scala, core/src/main/scala/io/iteratee/Iteratee.scala, core/src/main/scala/io/iteratee/IterateeModule.scala, core/src/main/scala/io/iteratee/internal/Input.scala, core/src/main/scala/io/iteratee/internal/Step.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala, tests/shared/src/test/scala/io/iteratee/XorTests.scala
This pull request makes a fairly large number of changes, including the following:
* `filterK` is not deprecated in favor of `filterF` for consistency.
* The helper classes in `Enumeratee` are reworked a bit.
* Unnecessarily restrictive constraints on some enumeratees are relaxed (e.g. `map` now only requires `Applicative`, not `Monad`.
* There are now `take`, `takeWhile`, `drop`, and `dropWhile` enumeratees.
* The `take`, etc. methods that returned iteratees in modules are renamed to `takeI` to avoid collisions with the new (preferred) iteratee methods.
* There are some new methods for constructing `Step` values.
=> Add take and drop enumeratees, etc.

tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala
I've confirmed that these fail before #72 and pass after it. I've also checked that all other cases with guards are exhaustive, but in general in the future I think we should avoid guards.
=> Add tests for iterateUntil cases reported in #71

core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/EnumerateeModule.scala, core/src/main/scala/io/iteratee/Iteratee.scala, core/src/main/scala/io/iteratee/IterateeModule.scala, core/src/main/scala/io/iteratee/internal/Step.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
`Iteratee.length` now returns a `Long` and is faster for chunked streams.
=> Fix #76, more efficient length iteratee

core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/EnumerateeModule.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala
Add a `takeWhileM` combinator to `Enumeratee`, using the bare `takeWhile` as a guide.
I don't suppose there's an already existing implementation of Vector#spanM anywhere?
=> Add Enumeratee.takeWhileM

tests/jvm/src/it/scala/io/iteratee/task/TaskFileModuleSuite.scala, tests/jvm/src/it/scala/io/iteratee/twitter/TwitterFileModuleSuite.scala, tests/jvm/src/test/scala/io/iteratee/twitter/RerunnableTests.scala, twitter/src/main/scala/io/iteratee/twitter/TwitterModule.scala, twitter/src/main/scala/io/iteratee/twitter/package.scala
In the previous version of iteratee-twitter, `Future.apply` was used to capture effects. This is now configurable, with the default future pool being used by default.
This PR also includes a drive-by fix for a deprecated Scalaz method.
=> Use future pool when working with Twitter futures

README.md, benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala, benchmark/src/test/scala/io/iteratee/benchmark/StreamingBenchmarkSpec.scala, build.sbt, monix/js/src/main/scala/io/iteratee/monix/MonixModule.scala, monix/jvm/src/main/scala/io/iteratee/monix/MonixModule.scala, project/build.properties, project/plugins.sbt, tests/jvm/src/it/scala/io/iteratee/monix/MonixFileModuleSuite.scala, tests/jvm/src/test/scala/io/iteratee/monix/MonixTests.scala
Avoids collisions between Cats instances for Monix's `Task` (see [Gitter](https://gitter.im/typelevel/cats?at=579782133383eb622144e9ff)).
=> Don't export Cats instances for Monix

LICENSE.scalaz
This should be in the history but got accidentally removed at some point—reinstating.
=> Reinstate Scalaz license file

scalaz/src/main/scala/io/iteratee/scalaz/ScalazModule.scala, twitter/src/main/scala/io/iteratee/twitter/TwitterModule.scala, twitter/src/main/scala/io/iteratee/twitter/package.scala
I know this code is likely to change soon, anyway, but this is a small fix that follows e.g. the behavior in scalaz-stream.
=> Don't fork in captureEffect

benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala, benchmark/src/main/scala/io/iteratee/benchmark/FileModuleBenchmark.scala, core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/Enumerator.scala, tests/jvm/src/main/scala/io/iteratee/tests/files/FileModuleSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/ArbitraryEnumerators.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/EqInstances.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala, tests/shared/src/test/scala/io/iteratee/EvalTests.scala, tests/shared/src/test/scala/io/iteratee/XorTests.scala
I'd like to rename `mapE` and `run` on `Enumerator`.
`mapE` is an inheritance from Scalaz, and I just don't like it much—if you already know what it means it's clear that it's about mapping an enumeratee, but something like `through` (which I've chosen here) or `transform` makes it clearer that you're attaching a pipe to a source.
`run` is borrowed from Play (and kind of from scalaz-stream), and I've found it potentially confusing when explaining the library to people, since for most interesting contexts it doesn't actually run anything. I've replaced it with `into` here (I think I'd prefer `to` if that weren't widely used in other libraries to indicate a conversion).
If either `mapE` or `run` were standard terms here, I'd be much more reluctant to replace them, but they're not really, …
=> Rename mapE and run

.travis.yml, build.sbt
These 2.10 tests slipped out during doge-ification.
=> Run more tests

core/src/main/scala/io/iteratee/Iteratee.scala, core/src/main/scala/io/iteratee/internal/Cont.scala, core/src/main/scala/io/iteratee/internal/Done.scala, core/src/main/scala/io/iteratee/internal/Step.scala
I just noticed that the `Monad` constraint and `F` in the return type don't seem to be necessary. The `Monad` constraint was inherited from Scalaz, but there the `zip` for iteratees is [broken](https://github.com/scalaz/scalaz/issues/1068), anyway.
=> Simplify zip's return type and constraint

core/src/main/scala/io/iteratee/internal/Done.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
This is a bug:
```scala
scala> import io.iteratee.modules.id._
import io.iteratee.modules.id._
scala> enumVector(Vector(1, 2, 3)).into(takeI(3).zip(takeI[Int](1)).flatMap(_ => consume))
res0: cats.Id[Vector[Int]] = Vector(2, 3)
```
When zipping two iteratees that end up done, the resulting chunk leftovers should always be the shorter of the leftovers of the two done iteratees. Before this change, if the first had no leftovers, the second's leftovers were used.
I've also moved `contramap` to the base class just to simplify things a bit.
=> Always return shorter leftovers when zipping done iteratees

benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala, build.sbt, monix/js/src/main/scala/io/iteratee/monix/TaskModule.scala, monix/jvm/src/it/scala/io/iteratee/monix/TaskFileModuleTests.scala, monix/jvm/src/main/scala/io/iteratee/monix/TaskModule.scala, monix/jvm/src/test/scala/io/iteratee/monix/TaskTests.scala, monix/shared/src/main/scala/io/iteratee/monix/DefaultTaskModule.scala, monix/shared/src/main/scala/io/iteratee/monix/MonixInstances.scala, monix/shared/src/main/scala/io/iteratee/monix/package.scala
This PR removes the monix-cats dependency from the iteratee-monix module in order to simplify the process of publishing new releases after a Cats update. Now users can decide whether they want to depend on monix-cats and use its instances (if the versions line up and that's an option), or to use the `MonadError[Task]` provided here.
In the immediate future this means that we can publish the 0.7.0 release as soon as Cats 0.8.0 is out, without waiting for a version of monix-cats for 0.8.0.
=> Update Monix and remove monix-cats

.travis.yml, benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala, benchmark/src/test/scala/io/iteratee/benchmark/InMemoryBenchmarkSpec.scala, benchmark/src/test/scala/io/iteratee/benchmark/StreamingBenchmarkSpec.scala, build.sbt
The Play results weren't very interesting, and I wanted an easy way to compare performance on Scala 2.12.0 (which play-iteratee isn't published for).
=> Update benchmark versions and remove Play

files/src/main/scala/io/iteratee/files/package.scala
Fixes #168. See #169 for an explanation of why this PR doesn't include new tests that fail before the fix.
I've also added `FutureModule` to the `future` signature to bring it into line with the other files modules.
=> Fix NPE in future files module

core/src/main/scala/io/iteratee/internal/Step.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
For your consideration. The test I wrote is maybe a little overkill: no real need to create an extra `EnumeratorAndValues`. I can try to simplify that if you like.
The added test fails without the fix, and passes with it.
=> fix odd case in Iteratee.foreach

core/src/main/scala/io/iteratee/IterateeModule.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
It's annoying to import the contents of a module and have `identity` clash with `Predef.identity` (I use `-Yno-predef` enough that I'm just now coming across this). This deprecation doesn't fix the annoyance, but it does set us up to fix it in the next release.
I also considered `idIteratee` and `iterateeIdentity` as names, but went with `identityIteratee` for the sake of consistency with `failIteratee` and to avoid confusion with `cats.Id`.
=> Rename and deprecated identity in iteratee module

core/src/main/scala/io/iteratee/Iteratee.scala, core/src/main/scala/io/iteratee/IterateeModule.scala, core/src/main/scala/io/iteratee/internal/Step.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
This is something I've wanted a few times now. I didn't really want to add `foldMapMOption` but ended up including it for the sake of consistency. 
I've removed `Step.foldMapOption` without a deprecation cycle since it wasn't really necessary and is marked as internal.
=> Add foldMapM iteratees

core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/IterateeInstances.scala, core/src/main/scala/io/iteratee/internal/Step.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala
Somehow #180 turned up a (pre-existing) bug involving the stack-safety of `sequenceI`, which is currently causing tests to fail occasionally. The issue is that `sequenceI` flat-maps recursively, which can cause problems on large chunks for monads that don't provide their own stack-safe recursive binding. For example:
```scala
import cats.Monad
import io.iteratee.{ Enumerator, Iteratee }
def checkStackSafety[F[_]: Monad]: F[Long] =
Enumerator.enumVector[F, Int]((0 to 10000).toVector).grouped(3).into(Iteratee.length)
``` 
And then:
```scala
scala> import cats.instances.option._
import cats.instances.option._
scala> checkStackSafety[Option]
java.lang.StackOverflowError
at scala.collection.immutable.Vector.take(Vector.scala:160)
at scala.collection.immutable.Vector.splitAt(Vector.scala:215) …
```
=> Make sequenceI stack-safe

core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/EnumerateeModule.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala
In an application I'm currently working on I'm needing to enumerate a bunch of values and write a high-level summary to one file and a more direct representation to another file, and having an enumeratee that supports injecting values (header lines, etc.) makes this more convenient.
=> Add enumeratees that inject values

core/src/main/scala/io/iteratee/Enumerator.scala, core/src/main/scala/io/iteratee/EnumeratorModule.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala
The new `enumIterable` is pretty self-explanatory. There are two main other changes:
`Enumerator.enumStream` no longer blows up when the chunk size is zero or smaller, and it's now possible to pass in a chunk size to the module version of `enumStream`.
=> Add enumIterable and minor changes to enumStream

core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/Iteratee.scala, core/src/main/scala/io/iteratee/IterateeModule.scala, core/src/main/scala/io/iteratee/internal/Step.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
This PR does three major things. The first thing is a change to the behavior you see when you bind an iteratee that's done with leftovers into another iteratee that's done with leftovers. The previous behavior made the binding associative in these cases, but it's not associative in similar cases (e.g. binding a continuation iteratee into an iteratee that's done with leftovers), anyway, and complicating the implementation to paper over one case seems kind of silly in retrospect.
To make this more concrete, here are two examples of broken associativity with this PR:
```scala
import cats.instances.option._, cats.syntax.all._
import io.iteratee.Iteratee, io.iteratee.internal.Step, io.iteratee.modules.option._
val done1 = Iteratee.fromStep(Step.doneWithLeftovers((), List(1, 2, 3)))
val done2 = …
```
=> Less leftovers

core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/EnumerateeModule.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala
This enumeratee is useful when you want to capture something like header-parsing logic in an enumerator instead of an enumeratee. One quick example—suppose you have a file like this:
```
3
cat
bat
dog
foo
```
…where the first line is a header that indicates how long each of the lines must be.
You could parse it like this:
```scala
import cats.instances.option._, io.iteratee.modules.option._
import scala.util.Try
val goodLines = enumerate("3", "cat", "bat", "dog", "foo")
val badLines = enumerate("3", "cat", "bat", "dog", "bird", "foo")
def validateLine(header: Int)(line: String): Option[String] =
if (line.size == header) Some(line) else None
val parseHeader = head[String].flatMapM {
case Some(line) => Try(line.toInt).toOption
case None => None
}
val parseLines = for {
header <- parseHeader …
```
=> Add remainderWithResult

core/src/main/scala/io/iteratee/Enumeratee.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala, tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
Note that these methods are intentionally not included in `EnumerateeModule`, since they should be used rarely.
=> Add enumeratees for observing chunks and rechunking

build.sbt, testing/shared/src/main/scala/io/iteratee/testing/IterateeSuite.scala
Builds for cats-1.0.0-RC2.  If this gets released, we can keep validating more projects downstream without reasoning about eviction.
If this doesn't get released, can bump again next week to cats-1.0.0.
=> Dependency upgrades

build.sbt
There's still no fs2 release for Cats 1.0.0, but we only need it for the benchmarks here, so it's not a big deal.
=> Cats 1.0.0

core/src/main/scala/io/iteratee/Enumeratee.scala, core/src/main/scala/io/iteratee/Enumerator.scala, testing/shared/src/main/scala/io/iteratee/testing/EnumeratorSuite.scala
close #158 
This was a bit of a pain in the ass due to the layers in this set of abstractions. There is likely a somewhat better way to do this, but at least the tests pass.
=> Make Enumerator monad laws pass (tailRecM)
