travisbrown/iteratee

- core/shared/src/test/scala/io/iteratee/IterateeSuite.scala
Confirms that [this Scalaz bug](https://github.com/scalaz/scalaz/issues/1068) is fixed.
> Add iteratee zipping test for scalaz/scalaz#1068

- benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala
- core/shared/src/main/scala/io/iteratee/Enumeratee.scala
- core/shared/src/main/scala/io/iteratee/Enumerator.scala
- core/shared/src/main/scala/io/iteratee/EnumeratorModule.scala
- core/shared/src/main/scala/io/iteratee/Input.scala
- core/shared/src/main/scala/io/iteratee/Iteratee.scala
This doesn't really have any impact on the current benchmarks, but it's a bit simpler and should help in some situations.
> Fix the collection type for chunks

- core/shared/src/main/scala/io/iteratee/Iteratee.scala
> Clean up take and friends a bit

- README.md
- benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala
- build.sbt
- core/shared/src/main/scala/io/iteratee/Enumeratee.scala
- core/shared/src/main/scala/io/iteratee/EnumerateeModule.scala
- core/shared/src/main/scala/io/iteratee/Enumerator.scala
- core/shared/src/main/scala/io/iteratee/EnumeratorModule.scala
- core/shared/src/main/scala/io/iteratee/Input.scala
- core/shared/src/main/scala/io/iteratee/Iteratee.scala
- core/shared/src/main/scala/io/iteratee/IterateeModule.scala
- core/shared/src/main/scala/io/iteratee/Step.scala
- core/shared/src/main/scala/io/iteratee/package.scala
- core/shared/src/test/scala/io/iteratee/EnumeratorSuite.scala
- core/shared/src/test/scala/io/iteratee/EqInstances.scala
- core/shared/src/test/scala/io/iteratee/IterateeSuite.scala
This PR is kind of a grab bag but I'm not going to worry about it because the project is still young.
> Some renaming, better benchmarks, etc.

- core/shared/src/main/scala/io/iteratee/Enumerator.scala
- core/shared/src/main/scala/io/iteratee/package.scala
- core/shared/src/test/scala/io/iteratee/BaseSuite.scala
- core/shared/src/test/scala/io/iteratee/EnumeratorSuite.scala
This is like a `finally` block for enumerators.
> Add ensure for enumerators

- core/src/main/scala/io/iteratee/Enumeratee.scala
- core/src/main/scala/io/iteratee/internal/Done.scala
- core/src/main/scala/io/iteratee/internal/Input.scala
- core/src/main/scala/io/iteratee/internal/Step.scala
- core/src/test/scala/io/iteratee/ArbitraryInstances.scala
- core/src/test/scala/io/iteratee/BaseSuite.scala
- core/src/test/scala/io/iteratee/EnumerateeSuite.scala
- core/src/test/scala/io/iteratee/IterateeSuite.scala
Now only missing a few things in `io.iteratee.internal`.
> Closer to 100% coverage

- core/src/main/scala/io/iteratee/Enumeratee.scala
- core/src/main/scala/io/iteratee/Enumerator.scala
- core/src/main/scala/io/iteratee/EnumeratorModule.scala
- core/src/main/scala/io/iteratee/Iteratee.scala
- core/src/main/scala/io/iteratee/IterateeModule.scala
- core/src/main/scala/io/iteratee/internal/Cont.scala
- core/src/main/scala/io/iteratee/internal/Done.scala
- core/src/main/scala/io/iteratee/internal/Step.scala
- core/src/test/scala/io/iteratee/EnumeratorSuite.scala
- core/src/test/scala/io/iteratee/EqInstances.scala
- core/src/test/scala/io/iteratee/IterateeSuite.scala
I'm pretty confident this is a good idea.
> Get rid of Ended

- core/src/main/scala/io/iteratee/internal/Step.scala
- tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala
- tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
[Reported](https://gitter.im/travisbrown/iteratee?at=56ad11ed8fbaf4220afa4d01) by @Crafter6432.
> Updates for changes in the cats snapshot

- benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala
- core/src/main/scala/io/iteratee/Enumerator.scala
- core/src/main/scala/io/iteratee/EnumeratorModule.scala
- tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala
As discussed [here](https://gitter.im/travisbrown/iteratee?at=56ad07a680ad69394a7b6a1e)
> Add generateM, modify iterate and iterateM to support termination

- benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala
- build.sbt
Based on a project reference for now, in lieu of a public build.
> Add benchmarks for fs2.

- build.sbt
- core/src/main/scala/io/iteratee/Iteratee.scala
- core/src/main/scala/io/iteratee/IterateeModule.scala
- tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
> Add foreach and discard for iteratees

- .travis.yml
- build.sbt
This was causing problems with `sbt +publishSigned`.
> Don't aggregate benchmark

- core/src/main/scala/io/iteratee/Enumerator.scala
- tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala
> Add reducedK

- core/src/main/scala/io/iteratee/Enumeratee.scala
- core/src/main/scala/io/iteratee/EnumerateeModule.scala
- core/src/main/scala/io/iteratee/Enumerator.scala
- core/src/main/scala/io/iteratee/Iteratee.scala
- tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala
- tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala
- tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
Changing these one more time—I want to avoid a confusing mix of `F` and `M` (and `K`) suffixes, so I'm just going with `M` everywhere.
> Naming consistency

- core/src/main/scala/io/iteratee/Enumeratee.scala
- core/src/main/scala/io/iteratee/EnumerateeModule.scala
- tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala
> Add Enumeratee.dropWhileM

- build.sbt
Same deal as [here](https://github.com/travisbrown/circe/pull/323).
> Remove Scoverage dependencies from POM

- files/src/main/scala/io/iteratee/files/FileModule.scala
- tests/jvm/src/main/scala/io/iteratee/tests/files/FileModuleSuite.scala
Also changed constant in ByteEnumerator to match the default
BufferedInputStream buffer size (and a power of 2).
> Implement readBytesFromStream Enumerator

- core/src/main/scala/io/iteratee/Enumeratee.scala
- core/src/main/scala/io/iteratee/Enumerator.scala
- core/src/main/scala/io/iteratee/internal/Step.scala
I think this gets us to appropriate constraints (see #109, #111), but I'll continue to keep an eye out.
> Relax some constraints

- core/src/main/scala/io/iteratee/Enumerator.scala
- core/src/main/scala/io/iteratee/Iteratee.scala
- core/src/main/scala/io/iteratee/internal/Step.scala
- files/src/main/scala/io/iteratee/files/FileModule.scala
- files/src/main/scala/io/iteratee/files/NonSuspendableFileModule.scala
- files/src/main/scala/io/iteratee/files/SuspendableFileModule.scala
- scalaz/src/it/scala/io/iteratee/scalaz/TaskFileModuleSuite.scala
- tests/jvm/src/main/scala/io/iteratee/tests/files/FileModuleSuite.scala
- tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
> Add iteratees for file writing

- .travis.yml
- tests/shared/src/main/scala/io/iteratee/tests/BaseSuite.scala
Thanks to @ilya-murzinov for pointing out that Travis CI was ignoring some failures.
(I hate Bash.)
> Make Travis CI fail appropriately

- core/src/main/scala/io/iteratee/Iteratee.scala
- core/src/main/scala/io/iteratee/IterateeModule.scala
- core/src/main/scala/io/iteratee/internal/Step.scala
- tests/shared/src/main/scala/io/iteratee/tests/IterateeSuite.scala
> Introduce a 'foldMap' variant for cats.Semigroup

- core/src/main/scala/io/iteratee/Enumerator.scala
- tests/shared/src/main/scala/io/iteratee/tests/EnumeratorSuite.scala
Addresses the question in #113. I've decided the convenience these methods add is worth the cost of some duplication.
> Add convenience methods on Enumerator

- benchmark/src/it/scala/io/iteratee/benchmark/FileModuleBenchmarkSpec.scala
- benchmark/src/main/scala/io/iteratee/benchmark/Benchmark.scala
- benchmark/src/main/scala/io/iteratee/benchmark/FileModuleBenchmark.scala
- benchmark/src/test/scala/io/iteratee/benchmark/InMemoryBenchmarkSpec.scala
- benchmark/src/test/scala/io/iteratee/benchmark/StreamingBenchmarkSpec.scala
- build.sbt
- fs2/src/main/scala/io/iteratee/fs2/TaskModule.scala
- fs2/src/main/scala/io/iteratee/fs2/package.scala
- fs2/src/test/scala/io/iteratee/fs2/TaskTests.scala
> Add fs2 module

- build.sbt
- project/plugins.sbt
Tests should pass (they do locally), but the fs2-cats artifact depends on Cats 0.8.1 and we should wait for that to be updated.
> Update Cats to 0.9.0

- core/src/main/scala/io/iteratee/Enumerator.scala
- core/src/main/scala/io/iteratee/internal/Step.scala
there's hardly anything here, but i figured, why keep it to myself?
> two very minor scaladocs improvements

- core/src/main/scala/io/iteratee/Enumeratee.scala
- tests/shared/src/main/scala/io/iteratee/tests/EnumerateeSuite.scala
This isn't really necessary but it can be convenient sometimes.
> Add into method to Enumeratee

- build.sbt
And a few other little things.
> Update catbird to 0.14.0

- core/src/main/scala/io/iteratee/internal/Step.scala
This change fixes cases like [this](https://github.com/travisbrown/iteratee/pull/218#issuecomment-342868520):
```scala
import cats.Id, cats.implicits._, io.iteratee._
val F = Iteratee.iterateeMonad[Id, Int]
val done = Iteratee.done[Id, Int, Int](1)
val whatever = Iteratee.fold[Id, Int, Int](0)(_ + _)
val fm = done.flatMap(_ => whatever)
val tr = F.tailRecM[Option[Int], Int](None) {
case None => F.map(done)(v => Left(Some(v)))
case Some(_) => F.map(whatever)(Right(_))
}
val values = Enumerator.enumerate[Id, Int](1, 2, 3)
val good = values.into(fm) // 6
val goodNow = values.into(tr) // now: 6, previously: 0
```
It also seems to me like it probably lines up a little more with reasonable expectations about what should happen when you feed a value to a completed step. Since feeding is entirely …
> Change behavior when calling feed methods on Done values

- .travis.yml
- build.sbt
- testing/shared/src/main/scala/io/iteratee/testing/EnumeratorSuite.scala
I'm adding cats-effect 1.0 support and it drops 2.10.
> Drop 2.10 support
